# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#   By considering the terms in the Fibonacci sequence whose values do
#   not exceed four million, find the sum of the even-valued terms.


MAX_VALUE = 4000000

fib = [0,1]
sum = 0
max_reached = false

require 'pp'

while !max_reached
  a = fib.shift
  fib[1] = fib[0] + a
  if (fib[1] <= MAX_VALUE)
    if fib[1]%2 ==0
      sum += fib[1]
    end
  else
    max_reached=true
  end
end


pp fib
pp sum
