# -*- coding: utf-8 -*-
#
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

#   1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#   It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

#   Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

require 'pp'


def pentagonal(n)
  (n*((n*3)-1))/2
end

search_space = 10000
pentagonals = []
pentagonals_h = {}

(1..search_space).each do |i|
  p = pentagonal(i)
  pentagonals << p
  pentagonals_h[p] = i
end

pentagonals.permutation(2).each do |pair|
  pair = pair.sort
  if pentagonals_h[pair[0]+pair[1]]
    if pentagonals_h[pair[1]-pair[0]]
      pp "D - #{pair[1]-pair[0]}"
    end
  end
end
