# -*- coding: utf-8 -*-
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#   Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
#   Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
#   Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
#
#   It can be verified that T285 = P165 = H143 = 40755.
#
#   Find the next triangle number that is also pentagonal and hexagonal.

require 'pp'

def triangle(n)
  (n*(n+1))/2
end

def pentagonal(n)
  (n*((n*3)-1))/2
end

def hexagonal(n)
  n*((n*2)-1)
end

h=143
p=165
t=285

answer = nil
current_hex = 0
current_pen = 0
current_tri = 0
while answer.nil?
  h+=1
  current_hex = hexagonal(h)
  while current_pen < current_hex
    p+=1
    current_pen = pentagonal(p)
  end
  if current_pen == current_hex
    while current_tri < current_hex
      t+=1
      current_tri = triangle(t)
    end
    if current_pen == current_tri
      answer = current_pen
    end
  end
end

# pp h
# pp p
# pp t
# pp triangle(t)
# pp pentagonal(p)
# pp hexagonal(h)
pp current_pen
